name: Cypress E2E Tests
on:
  push:
    branches:
      - main
jobs:
  execute_cypress_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies 
        run: npm ci
      - name: Run Cypress tests
        run: npm run cypress:run



  #     - name: Merge test results && Generate report
  #       if: always() # always run even if the previous step fails
  #       run: |
  #               npm run combine-reports
  #               npm run generate-report
  #     - name: Upload report
  #       uses: actions/upload-artifact@v3
  #       if: always() # always run even if the previous step fails
  #       with:
  #         name: cypress-report
  #         path: "**/cypress/reports/ci-reports/junit"
  # analyze-results:
  #   runs-on: ubuntu-latest
  #   needs: execute_cypress_test # job depends on execute_cypress_test
  #   if: always()
  #   steps:
  #     - name: download artifacts
  #       uses: actions/download-artifact@v3
  #     - name: Publish Test Report
  #       uses: mikepenz/action-junit-report@v3
  #       with:
  #         report_paths: "**/cypress/reports/ci-reports/junit/result*.xml"
  #         detailed_summary: true